/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OncButton {
        /**
          * @default 'primary'
         */
        "color": 'primary' | 'neutral';
    }
}
declare global {
    interface HTMLOncButtonElement extends Components.OncButton, HTMLStencilElement {
    }
    var HTMLOncButtonElement: {
        prototype: HTMLOncButtonElement;
        new (): HTMLOncButtonElement;
    };
    interface HTMLElementTagNameMap {
        "onc-button": HTMLOncButtonElement;
    }
}
declare namespace LocalJSX {
    interface OncButton {
        /**
          * @default 'primary'
         */
        "color"?: 'primary' | 'neutral';
    }
    interface IntrinsicElements {
        "onc-button": OncButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "onc-button": LocalJSX.OncButton & JSXBase.HTMLAttributes<HTMLOncButtonElement>;
        }
    }
}
